### PR TITLE
Update CardBrand.java regex, add support for MIR cardBrand

### PR DESCRIPTION
**Pull request by mbayerPK**
Update CardBrandTest.java for changed regex and MIR tests

> I really appreciate your interest in Credit Card Number. At this point, I am not accepting any pull requests or contributions, since I am trying to figure out copyright and/ or patent issues.
>
> Please feel free to file bug reports and enhancement requests, though, and I will do my best to address them quickly.
>
> **Sualeh Fatehi** <sualeh@hotmail.com>

### CODE REVIEW

**Comment by sualeh** [comment]
@mbayerPK - thanks for the contribution. I will request all of you to fill out a Contributor License Agreement. Stay tuned for details on how to do that.
Please could you consider the following changes:
1. The Wikipedia article [Payment card number](https://en.wikipedia.org/wiki/Payment_card_number) says MIR card numbers can be 16 or 19 digits long. Please could you correct the regular expression.
2. Please add unit tests for JCB card numbers starting with 2131 and 1800.
3. Ensure that all unit tests pass - AccountNumberCompleteTest is failing

**Comment by mbayerPK** [comment]
will do thanks for the heads up!

**Comment by mbayerPK** [comment]
To address @sualeh feedback directly:

1. The  [https://en.wikipedia.org/wiki/Payment_card_number](Payment Card Number) link says that MIR cards can be 16 through 19 digits in length rather than 16 or 19 digits in length (16-19 , vs 16,19). I couldn't find any good testing data for a 19 digit MIR card however.

2. I have found good data for the 15 digit JCB cards beginning with 1800 and added that. However I could find no ccn data for JCB cards beginning with 2131. I did find data for 15 digit JCB cards beginning with 2100 so I am using that and changing the regex accordingly. Lastly for this point, the  [https://en.wikipedia.org/wiki/Payment_card_number](Payment Card Number) does say that JCB beginning with 35 can be from 16 through 19 digits in length, so I updated the regex and tests accordingly for this as well.

3. Will fix the integration tests

**Comment by sualeh** [comment]
Thanks, @mbayerPK. Do you have a link to the test data that you used for JCB? I will merge your changes in, and make some minor tweaks.

**Comment by mbayerPK** [comment]
Dear @sualeh,
I got my test data for 15 digit and 16 digit JCB from [Get Credit Cards](https://www.getcreditcardnumbers.com/)  (specifying the 15 digit JCB and/or 16 digit JCB formats)
I got the 19 digit JCB test data from [Free Formatter](https://www.freeformatter.com/credit-card-number-generator-validator.html), you can see one 19 digit example in the JCB section and can refresh the page for new numbers.

**Pull request merged**
